- name: Build iOS Project
  run: |
    xcodebuild -project Overlay.xcodeproj \
      -scheme Overlay \
      -sdk iphoneos \
      -configuration Release \
      CODE_SIGN_IDENTITY="iPhone Developer" \
      PROVISIONING_PROFILE_SPECIFIER="YOUR_PROFILE_NAME" \
      PRODUCT_BUNDLE_IDENTIFIER="com.zwcam.overlay"
  env:
    CERTIFICATE_P12: ${{ secrets.CERTIFICATE_P12 }}
    PROVISIONING_PROFILE: ${{ secrets.PROVISIONING_PROFILE }}
    P12_PASSWORD: ${{ secrets.P12_PASSWORD }}
