- name: Decode and Show Team ID from Provisioning Profile
  run: |
    echo "$PROVISIONING_PROFILE" | base64 -d > profile.mobileprovision
    echo "🔍 Extracting Team ID..."
    security cms -D -i profile.mobileprovision | grep -A1 TeamIdentifier
  env:
    PROVISIONING_PROFILE: ${{ secrets.PROVISIONING_PROFILE }}
