
name: Build iOS dylib

on:
  push:
    branches: [ main ]

jobs:
  build:
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v2
      - name: Build dylib
        run: |
          xcodebuild -project Overlay.xcodeproj -scheme Overlay -sdk iphoneos -configuration Release
