name: Build iOS

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build:
    runs-on: macos-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup provisioning profile and certificate
        run: |
          echo "$CERTIFICATE_P12" | base64 -d > certificate.p12
          echo "$PROVISIONING_PROFILE" | base64 -d > profile.mobileprovision
          mkdir -p ~/Library/MobileDevice/Provisioning\ Profiles
          cp profile.mobileprovision ~/Library/MobileDevice/Provisioning\ Profiles/
          security create-keychain -p "" build.keychain
          security import certificate.p12 -k build.keychain -P "$P12_PASSWORD" -T /usr/bin/codesign
          security list-keychains -s build.keychain
          security default-keychain -s build.keychain
          security unlock-keychain -p "" build.keychain
        env:
          CERTIFICATE_P12: ${{ secrets.CERTIFICATE_P12 }}
          PROVISIONING_PROFILE: ${{ secrets.PROVISIONING_PROFILE }}
          P12_PASSWORD: ${{ secrets.P12_PASSWORD }}

      - name: Build iOS Project
        run: |
          xcodebuild -project Overlay.xcodeproj \
            -scheme Overlay \
            -sdk iphoneos \
            -configuration Release \
            DEVELOPMENT_TEAM=VW24HLY7HY \
            CODE_SIGN_IDENTITY="iPhone Developer" \
            PROVISIONING_PROFILE_SPECIFIER="zwCam" \
            PRODUCT_BUNDLE_IDENTIFIER="com.zwcam.overlay" \
            clean build

      - name: Find built app
        id: find_app
        run: |
          APP_PATH=$(find ./build -name "*.app" | head -n 1)
          echo "app_path=$APP_PATH" >> $GITHUB_OUTPUT

      - name: Create IPA
        run: |
          mkdir -p Payload
          cp -r "${{ steps.find_app.outputs.app_path }}" Payload/
          zip -r Overlay.ipa Payload
        shell: bash

      - name: Upload IPA Artifact
        uses: actions/upload-artifact@v3
        with:
          name: Overlay.ipa
          path: Overlay.ipa
